### ISSUE TITLE
Project report 

### ISSUE THREAD

**Issue by ctseng12** [psych-214-fall-2016/project-red#32]
### Logistical
Do we want to make a PDF or a Markdown file? I personally think Markdown would be easier for everyone to edit. 

### Organization
I was thinking we can make a separate folder called `/project-red/report` to put the report in and a subfolder `/project-red/report/figures` to put relevant figures.

**Comment by zzbalews** [comment]
Let's do Markdown if that's easier!

Does a Markdown file execute code or is it fixed? Some of our steps take a
long time, does that matter?

**Comment by ctseng12** [comment]
I don't think markdown executes code - do we need it to?

**Comment by jcbmiller94** [comment]
I agree about the markdown file format! These 'results' destinations should be where any images and plots are saved in the end of the scripts, correct? 

Working on changing that, but first trying to understand what's happening with these damn realignment parameters

**Comment by zzbalews** [comment]
Just to clarify to make sure I understand:

We will have directory `project-red/report/figures` in which we all save
the figures we want to include in the final report.

Our functions also produce nii files and other things that don't
necessarily go in the report. Those things should not be saved in this
figures dir, right?

**Comment by ctseng12** [comment]
Awesome, markdown it is then. 

whoops did not read - yes to @zzbalews

**Comment by jcbmiller94** [comment]
Hey, so I'm still working out some stuff with the code. Namely, I wasn't using a smoothed reference volume, and I'm adjusting some plotting settings. I'm going to let it run overnight, and I'll upload it all in the morning and early afternoon tomorrow!

**Comment by jcbmiller94** [comment]
anything else we're missing at this point?

**Comment by zzbalews** [comment]
Sorry I'm so slow, I'm working on the self evaluation. (My brain is frozen. I can't get past 2 pages.)

I'm going to add a couple of figures for (1) showing that our registration works on a known transformation and (2) what happens when we transform some real subjects. I have all of the code, I just have to organize the plots and add them to the repo.

**Comment by jcbmiller94** [comment]
@zzbalews don't worry about it at all! we still have plenty of time! Still working on my figures and such too. I'll we in the lab tomorrow afternoon, we can reconvene then and I'll keep you posted on my pushing and such (and eventually we can merge my pull request)

**Comment by zzbalews** [comment]
@cmusefish @mpnagle I looked through our subject registrations again, and I realized I did a terrible job with the skull-stripping (chunks of the brain are missing!) and that might explain why some of our subjects looked weird and squishy. 

Chris-- Would you have time to run your skull-stripping function on a few subjects? 

Michael-- If Chris can help us, would you want to fix this? I don't think it would be too much work (we should just have to find the landmarks again) but we might be pressed for time since each registration takes >1 hr.

**Comment by cmusefish** [comment]
Hey. So sorry I didnt get back to you sooner. FSL doesnt work on my
computer so i have to do it in the office. Im gonna head there soon. I just
got back from Tahoe. I'll send you a few skull stripped files.

**Comment by zzbalews** [comment]
Hey Chris, don't worry about it! Sorry I don't follow up on this with you.
We like the results we have, and we don't need new versions of the skull
stripped images.

I hope skiing was fun!!

**Comment by cmusefish** [comment]
It was great. I'm sorry I was not more helpful:/
